app/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views


# app_name = 'app'
urlpatterns = [
    url(r'^$', views.index, name='index_app'),
    url(r'^questions_edit$', views.index, name='questions_edit'),
    # url(r'^questions$', views.questionnaire, name='questions'),
    # ex: /galho/5/
    url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    # ex: /galho/5/results/
    url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    # ex: /polls/5/vote/  # nao tem votos nesse app
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),

# urls for the initial part
    url(r'^points$', views.poi_list, name='points'),
    url(r'^points2$', views.poi_list2, name='points2'),
    url(r'^weather$', views.poi_list2, name='weather'),
    url(r'^points_amir$', views.poi_list_amir, name='points_amir'),
    url(r'^testando$', views.testando, name='testando'),
    url(r'^model$', views.model, name='model'),
    # url(r'^query$', views.query, name='query'),
    url(r'^grs$', views.grs, name='grs'),
    url(r'^links$', views.links, name='links'),
    url(r'^contact$', views.contact, name='contact'),
    url(r'^about', views.about, name='about'),


    ### urls created for the questions
    url(r'^prospection$', views.prospection, name='prospection'),
    url(r'^natural$', views.natural, name='natural'),
    # url(r'^civil$', views.civil, name='civil'),
    url(r'^dams$', views.dams, name='dams'),
    url(r'^railways$', views.railways, name='railways'),
    url(r'^foundations$', views.foundations, name='foundations'),

    url(r'^oil$', views.oil, name='oil'),
    url(r'^gas$', views.gas, name='gas'),
    url(r'^mining$', views.mining, name='mining'),

    url(r'^landslides$', views.landslides, name='landslides'),
    url(r'^earthquakes$', views.earthquakes, name='earthquakes'),
    url(r'^volcanism$', views.volcanism, name='volcanism'),

    url(r'^sinkholes$', views.sinkholes, name='sinkholes'),
    url(r'^peat$', views.peat, name='peat'),
]

plot/urls.py
from django.conf.urls import url, include, patterns
from django.contrib import admin
from . import views

#####################################
from datetime import datetime
# from plot.forms import BootstrapAuthenticationForm


urlpatterns = [
    url(r'^$', views.home, name='home2'),
    url(r'^$', views.home, name='home_plot'),
    url(r'plot^$', views.index_plot, name='plot'),

    url(r'^figures$', views.figures, name='figures'),
    url(r'^plotando$', views.plotando, name='plotando'),
    url(r'^contas$', views.index_math, name='contas'),
    url(r'^contas_2p$', views.index_math_2p, name='contas_2p'),

    url(r'^txt$', views.text_output, name='txt'),
]


#
# urlpatterns = patterns('',
# url(r'^$', views.index, name='index'))

tree/urls.py
from django.conf.urls import url, include
from django.contrib import admin
#####################################
from datetime import datetime
from django.conf.urls import patterns, url
from app.forms import BootstrapAuthenticationForm

# urls for external applications:
urlpatterns = [
    url(r'^app/', include('app.urls')),
    url(r'^admin/', admin.site.urls,name = 'adm'),
    url(r'^plot/', include('plot.urls')),
    url(r'^hw1/', include('hw1.urls')),
    url(r'^lua/', include('lua.urls')),
    url(r'^questions/', include('questions.urls')),
    # url(r'^contacts/', include('contacts.urls')),

# # urls for the initial part app
    url(r'^$', 'app.views.home', name='home'),
    url(r'^in_construction$', 'app.views.in_construction', name='in_construction'),
    url(r'^query$', 'app.views.query', name='query'),
    url(r'^questions$', 'app.views.questionnaire', name='questions'),
    url(r'^civil$', 'app.views.civil', name='civil'),   # To use the adresses directly

# # urls for the geolocation and cloud part lua
    url(r'^geolocation$', 'lua.views.geolocation', name='geolocation'),
        url(r'^cloud$', 'lua.views.cloud', name='cloud'),

# urls already installed
    url(r'^login/$',
        'django.contrib.auth.views.login',
        # 'login',
        {
            'template_name': 'initial/login.html',
            'authentication_form': BootstrapAuthenticationForm,
            'extra_context':
            {
                'title':'Log in',
                'year':datetime.now().year,
            }
        },
        name='login'),
    url(r'^logout$',
        'django.contrib.auth.views.logout',
        {
            'next_page': '/',
        },
        name='logout'),
]

plot/models.py
from django.db import models

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text


#####################################################################################################
# # # From the Django for scientists tutorial
# This works as forms.py
from django.forms import ModelForm
# from math import pi

class Input(models.Model):
    r = models.FloatField(
        verbose_name=' amplitude (m)', default=1.0)
    s = models.FloatField(
        verbose_name=' damping coefficient (kg/s)', default=2.0)
    t = models.FloatField(
        verbose_name=' frequency (1/s)', default=2*3.141516)
    u = models.FloatField(
        verbose_name=' time interval (s)', default=18)
    f = models.CharField(
        verbose_name=' txt filename ', max_length=200, default = 'out-views_2p')

class InputForm(ModelForm):
    class Meta:
        model = Input
#         fields = ['A', 'b', 'w', 'T']
        fields = ['r', 's', 't', 'u','f']

plot/views.py
from django.shortcuts import render
# from django.shortcuts import render, render_to_response, get_object_or_404
from django.http import HttpResponse, HttpRequest
from django.template import loader, RequestContext
# from django.views import generic
from datetime import datetime
# from plot.models import *
# from .models import Question

def home(request):
    assert isinstance(request, HttpRequest)
    return render(request,'plot/home_plot.html',context_instance = RequestContext(request,
        {'title':'In Construction!',
            'message':'Main home page! In apk_project!',
            'content': 'This is the text of the main page, here we can write whatever we want!!!....',
            'year':datetime.now().year,}))
#    return HttpResponse("Primeiro passo pra plotagem! says hello world!")

def index_plot(request):
    assert isinstance(request, HttpRequest)
    return render(request,'plot/plot.html',context_instance = RequestContext(request,
        {'title':'Home page of plot, inside apk_project!, In Construction!',
            'message':'Your application description page (index-index)- change in app/views.py',
            'content': 'This is the text of the main page, here we can write whatever we want!!!....',
            'year':datetime.now().year,}))
#    return HttpResponse("Primeiro passo pra plotagem! says hello world!")

def figures(request):
    assert isinstance(request, HttpRequest)
    return render(request,'plot/figures.html',context_instance = RequestContext(request,
        {'title':'Plotando',
            'message':'Your application description page (bor base-B1)- change in app/views.py',
            'content': 'This is the text of the page, here we can write quite a lot....',
            'year':datetime.now().year,}))

def plotando(request):
    """Renders the home page."""
    assert isinstance(request, HttpRequest)
    return render(request, 'plot/plotando.html', context_instance = RequestContext(request,
        {'title':'Extra page to test PLOTS',
            'message':'Your application description page (bor base-B1)- change in app/views.py',
            'content': 'This is the text of the page, here we can write quite a lot....',
            'year':datetime.now().year,}))


def text_output(request):
#    return HttpResponse("<strong>    ...In Construction! <strong>")
    assert isinstance(request, HttpRequest)
    return render(request,'plot/txt.html',context_instance = RequestContext(request,
        {'title':'    ...In Construction!',
            'message':'Your application description page - change in app/views.py',
            'content': 'This is the text of the main page, here we can write whatever we want!!!....',
            'year':datetime.now().year,}))

# ##############################################################################################
# # # # From the Django for scientists tutorial modified
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.http import HttpResponse
# from plot.models import InputForm
from . models import InputForm
# from plot.compute import compute, soma, mean
# from plot.compute import *
from . compute import *

## ## Function for the graph.  template = contas
def index_math(request):
    a = None  # initial value of result
    b = None  # initial value of result
    c = None  # initial value of result
    if request.method == 'POST':
        form = InputForm(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            r = form.r
            s = form.s
            t = form.t
            u = form.u
            a = compute(r)
            b = soma(r,s,t,u)
            c = mean(r,s,t,u)
    else:
        form = InputForm()

    return render_to_response('plot/contas.html',
            {'form': form,
             'b': '%.2f' % b if isinstance(b, float) else '',
             'a': '%.2f' % a if isinstance(a, float) else '',
             'c': '%.2f' % c if isinstance(c, float) else ''
             }, context_instance=RequestContext(request))


##########################################################################
## ## function for the view I created, with txt file. Template = contas_2p
def index_math_2p(request):
    a = None  # initial value of result
    b = None  # initial value of result
    c = None  # initial value of result
    d = None  # initial value of result
#    f = None  # initial value of result
    if request.method == 'POST':
        form = InputForm(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            # Creating input variables
            r = form.r
            s = form.s
            t = form.t
            u = form.u
            f = form.f  # for filename
            # For the output
            a = compute(r) # for the compute.py script
            b = soma(r,s,t,u)
            c = mean(r,s,t,u)
            d = write_txt(r,s,t,u,f)
            ############################
            ### For txt file directly from views
            # # # out_file_nm = str('outputfile_from_views_index_math_2p.txt')
            # out_file_nm = str( f + '.txt')
            # fh = open(out_file_nm, 'w')
            # fh.write('Testing output file in views (index_math_2p) for program APK, app plot \n\n')
            # fh.write('Input 1:  ')
            # fh.write(str(r) +'\n')
            # fh.write('Input 2:  ')
            # fh.write(str(s) +'\n')
            # fh.write('Input 3:  ')
            # fh.write(str(t) +'\n')
            # fh.write('Input 4:  ')
            # fh.write(str(u) +'\n\n')
            # fh.write('Sum:  ')
            # fh.write(str(b) +'\n')
            # fh.write('Mean:  ')
            # fh.write(str(c) +'\n')
            # fh.write('Sin of input 1:  ')
            # fh.write(str(a) +'\n')
            # fh.close()

    else:
        form = InputForm()
    return render_to_response('plot/contas_2p.html',
            {'form': form,
             'b': '%.2f' % b if isinstance(b, float) else '',
             'a': '%.2f' % a if isinstance(a, float) else '',
             'c': '%.2f' % c if isinstance(c, float) else '',
             'd': d,
             }, context_instance=RequestContext(request))
####################################################################################

## ## Testing to get results in different pages:  template = contas
# def index_math_3p(request):
#     a = None  # initial value of result
#     b = None  # initial value of result
#     c = None  # initial value of result
#     d = None  # initial value of result
#     f = None  # initial value of result
#     if request.method == 'POST':
#         form = InputForm(request.POST)
#         if form.is_valid():
#             form = form.save(commit=False)
#             r = form.r
#             s = form.s
#             t = form.t
#             u = form.u
#             f = form.f  # for filename
#             a = compute(r) # for the compute.py script
#             b = soma(r,s,t,u)
#             c = mean(r,s,t,u)
#             d = write_txt(r,s,t,u,f)
#         else:
#             form = InputForm()
#
#     return render_to_response('plot/contas_2p.html',
#             {'form': form,
#              'b': '%.2f' % b if isinstance(b, float) else '',
#              'a': '%.2f' % a if isinstance(a, float) else '',
#              'c': '%.2f' % c if isinstance(c, float) else '',
#              'd': d,
#              }, context_instance=RequestContext(request))

plot/templates/plot/contas.html
<!DOCTYPE html>

{% block content %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
            <p>  </p><br />
            <p>  </p><br />
<form method="post" action="">{% csrf_token %}

    <p><strong>First calculations! <br /> Input numbers <br />  Testing for simple math  </strong></p>
            <p>  </p><br />
        <p> Question 1    {{ form.r }} </p>
                <p>  </p><br />
        <p> Question 2    {{ form.s }} </p>
                <p>  </p><br />
        <p> Question 3    {{ form.t }} </p>
                <p>  </p><br />
        <p> Question 4    {{ form.u }} </p>

                <p>  </p><br />
            <p> <input type="submit"value="calculate" /> </p>


    <p> The sum is =
    {% if b != '' %}
    {{ b }}
    {% endif %}</p>

    <p> The mean is =
    {% if c != '' %}
    {{ c }}
    {% endif %}</p>

    <p> The sin of input question 1 is =
    {% if a != '' %}
    {{ a }}
    {% endif %}</p>

</form>

</body>

{% endblock %}

<!--

# Make info needed in the web form
form = InputForm()
# Make HTML code
render_to_response('hw1.html',
    {'form': form}, context_instance=RequestContext(request))


<form method="post" action="">
<div style='display:none'>
<input type='hidden' name='csrfmiddlewaretoken'
value='oPWMuuy1gLlXm9GvUZINv49eVUYnux5Q' /></div>
    Hello, World! The sine of <input type="text" name="r" id="id_r" />
    <input type="submit" value="equals" />
</form>  -->

plot/templates/plot/contas_2p.html
{% extends "initial/layout.html" %}

{% block content %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
            <p>  </p><br />
            <p>  </p><br />
<form method="post" action="">{% csrf_token %}

    <p> <strong>What is your project name?  (also output filename.txt)   ...........        {{ form.f }} </strong></p>

                <p>  </p><br />

    <p><strong>First calculations! <br /> Input numbers <br />  Testing for simple math (input float!) </strong></p>
            <p>  </p><br />
        <p> Question 1...........   answer =  {{ form.r }} </p>
                <p>  </p><br />
        <p> Question 2...........   answer =  {{ form.s }} </p>
                <p>  </p><br />
        <p> Question 3...........   answer =  {{ form.t }} </p>
                <p>  </p><br />
        <p> Question 4...........   answer =  {{ form.u }} </p>
                <p>  </p><br />

        <p> <input type="submit"value="calculate" /> </p>
                <p>  </p><br />


     <p><a href="txt">Download txt File</a></p>
                <p>  </p><br />


                    <p> </p> <br />
      <p> testing for filename.txt...........   answer =  {{ form.f }} </p>





                    <p> </p> <br />
<a href='d' target='_blank'>download</a>
              <p> </p> <br />

<a href="out-views_2p.txt" target="_blank">Download txt</a>



    <p> The sum is =
    {% if b != '' %}
    {{ b }}
    {% endif %}</p>

    <p> The mean is =
    {% if c != '' %}
    {{ c }}
    {% endif %}</p>

    <p> The sin of input question 1 is =
    {% if a != '' %}
    {{ a }}
    {% endif %}</p>


</form>


</body>

{% endblock %}

<!--

# Make info needed in the web form
form = InputForm()
# Make HTML code
render_to_response('hw1.html',
    {'form': form}, context_instance=RequestContext(request))


<form method="post" action="">
<div style='display:none'>
<input type='hidden' name='csrfmiddlewaretoken'
value='oPWMuuy1gLlXm9GvUZINv49eVUYnux5Q' /></div>
    Hello, World! The sine of <input type="text" name="r" id="id_r" />
    <input type="submit" value="equals" />
</form>  -->

plot/templates/plot/figures.html
<!DOCTYPE html>
<html>
<head>
        <h2>{{title}}</h2>
        <h3>{{ message }}</h3>
        {{content}}

</head>
<body>
<h1>Are we going to see?...</h1>
hello world! <strong>{{ boldmessage }}</strong><br />



            <p></p><br />
            <p></p><br />
                <a href="{{request.META.HTTP_REFERER}}">Back</a>
            <p> </p>

</body>
</html>

plot/templates/plot/grafico2.html
<!DOCTYPE html>

{% block content %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
            <p>  </p><br />
            <p>  </p><br />
<form method="post" action="">{% csrf_token %}

    <p><strong>First calculations! <br /> Input numbers <br />  Testing for simple math  </strong></p>
            <p>  </p><br />
        <p> Question 1    {{ form.r }} </p>
                <p>  </p><br />
        <p> Question 2    {{ form.s }} </p>
                <p>  </p><br />
        <p> Question 3    {{ form.t }} </p>
                <p>  </p><br />
        <p> Question 4    {{ form.u }} </p>

                <p>  </p><br />
            <p> <input type="submit"value="calculate" /> </p>


    <p> The sum is =
    {% if b != '' %}
    {{ b }}
    {% endif %}</p>

    <p> The mean is =
    {% if c != '' %}
    {{ c }}
    {% endif %}</p>

    <p> The sin of input question 1 is =
    {% if a != '' %}
    {{ a }}
    {% endif %}</p>

</form>

</body>

{% endblock %}

<!--

# Make info needed in the web form
form = InputForm()
# Make HTML code
render_to_response('hw1.html',
    {'form': form}, context_instance=RequestContext(request))


<form method="post" action="">
<div style='display:none'>
<input type='hidden' name='csrfmiddlewaretoken'
value='oPWMuuy1gLlXm9GvUZINv49eVUYnux5Q' /></div>
    Hello, World! The sine of <input type="text" name="r" id="id_r" />
    <input type="submit" value="equals" />
</form>  -->

plot/templates/plot/home.html
<!DOCTYPE html>
<html>
    <head>
        <h1>{{title}}</h1>
        <h2>{{ message }}</h2>
        <h3>{{content}}</h3> <br/>

    </head>

    <body>


        <div class="col-md-4">
     <p><a href="plot">plot main page</a></p>
                <p>  </p><br />
    </div>


            <p></p><br />
            <p></p><br />
                <a href="{{request.META.HTTP_REFERER}}">Back</a>
            <p> </p>


    </body>
</html>

<!--

    <div class="col-md-4">
     <p><a href="figures">Figures</a></p>
                <p>  </p><br />
    </div>

    <div class="col-md-4">
     <p><a href="plotando">Plotando</a></p>
                <p>  </p><br />
    </div>

    <div class="col-md-4">
        <p><a href="txt">Txt File</a></p>
                <p>  </p><br />
    </div>
-->

plot/templates/plot/home_plot.html
{% extends "initial/layout.html" %}

{% block content %}


    <head>
        <h1>{{title}}</h1>
        <!--<h2>{{ message }}</h2>-->
        <!--<h3>{{content}}</h3> <br/>-->

    </head>

    <body>
        <br /><br /><br />

        <div class="col-md-4">
     <p><a href="plot">.......</a></p>
                <p>  </p><br />
    </div>


        <!--<div class="col-md-4">-->
     <!--<p><a href="lua">Lua</a></p>-->
                <!--<p>  </p><br />-->
    <!--</div>-->


        <!--<div class="col-md-4">-->
     <!--<p><a href="home">home</a></p>-->
                <!--<p>  </p><br />-->
    <!--</div>-->




    </body>
</html>


{% endblock %}

<!--

    <div class="col-md-4">
     <p><a href="figures">Figures</a></p>
                <p>  </p><br />
    </div>

    <div class="col-md-4">
     <p><a href="plotando">Plotando</a></p>
                <p>  </p><br />
    </div>

    <div class="col-md-4">
        <p><a href="txt">Txt File</a></p>
                <p>  </p><br />
    </div>
-->

plot/templates/plot/index_plot.html
<!DOCTYPE html>
<html>

{% block content %}
    <head>
        <h1>{{title}}</h1>
        <h2>{{ message }}</h2>
        <h3>{{content}}</h3> <br/>

    </head>
<body>

    <div class="col-md-4">
     <p><a href="contas_2p">Math</a></p>
                <p>  </p><br />
    </div>

    <div class="col-md-4">
     <p><a href="figures">Figures</a></p>
                <p>  </p><br />
    </div>

    <div class="col-md-4">
     <p><a href="plotando">Plotando</a></p>
                <p>  </p><br />
    </div>

    <div class="col-md-4">
        <p><a href="txt">Txt File</a></p>
                <p>  </p><br />
    </div>

            <p></p><br />
            <p></p><br />
                <a href="{{request.META.HTTP_REFERER}}">Back</a>
            <p> </p>


</body>
</html>

{% endblock %}

plot/templates/plot/layout.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }} - GRS-RADAR</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/site.css' %}" />
    <script src="{% static 'app/scripts/modernizr-2.6.2.js' %}"></script>
</head>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    </button>
                        <a href="/" class="navbar-brand">Home</a>
                        </div>
                        <div class="navbar-collapse collapse">
                        <ul class="nav navbar-nav">
                    <li><a href="{% url 'query' %}">Query</a></li>
                    <li><a href="{% url 'grs' %}">GRS TU Delft</a></li>

                    <li><a href="{% url 'contact' %}">Researchers</a></li>
                    <li><a href="{% url 'links' %}">Inspiration</a></li>
                    <li><a href="{% url 'about' %}">About Me</a></li>
                </ul>
                {% include 'initial/loginpartial.html' %}
            </div>
        </div>
    </div>

    <div class="container body-content">


{% block content %}{% endblock %}
        <hr/>

        <footer>
           <!--  <a class="btn btn-default" href="{{request.META.HTTP_REFERER}}">Back</a> -->
            <p> </p>
            <br />
            <p> </p>
            <p></p>
            <a href="{{request.META.HTTP_REFERER}}">Back</a>
            <p> </p>
            <br />
            <p> </p>
            <p></p>

          <!--  <p>&copy; {{ year }} - Created by Luciana Toyoda using Django Application</p>  -->

        </footer>
        </div>
    </div>

    <script src="{% static 'app/scripts/jquery-1.10.2.js' %}"></script>
    <script src="{% static 'app/scripts/bootstrap.js' %}"></script>
    <script src="{% static 'app/scripts/respond.js' %}"></script>
{% block scripts %}{% endblock %}
   </div>
</body>

   </div>

</html>

plot/templates/plot/plotando.html
<!DOCTYPE html>
<html>
    <head>
        <h2>{{title}}</h2>
        <h3>{{ message }}</h3>
        {{content}}

    </head>

    <body>
        <h1>...</h1>
        ! <strong>{{ boldmessage }}</strong><br />

                <p></p><br />
            <p></p><br />
                <a href="{{request.META.HTTP_REFERER}}">Back</a>
            <p> </p>
    </body>
</html>

plot/templates/plot/txt.html
<!DOCTYPE html>
<html>
    <head>
        <h1>{{title}}</h1>
        <h2>{{ message }}</h2>
        <h3>{{content}}</h3> <br/>

    </head>

    <body>
        ..<br/>
         <strong>{{ boldmessage }}</strong><br/>

                <p></p><br />
            <p></p><br />
                <a href="{{request.META.HTTP_REFERER}}">Back</a>
            <p> </p>
    </body>
</html>